name: Release

on:
  release:
  workflow_dispatch:
  

jobs:
  releaser:
    name: Release

    permissions:
      contents: write

    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
